// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCSYRCZhDyP7JZ-X8Sd8Xc93MIezfJt1kM',
    appId: '1:1025879425987:web:16b1c54640dd8c8b3f3376',
    messagingSenderId: '1025879425987',
    projectId: 'card-app-c9c1a',
    authDomain: 'card-app-c9c1a.firebaseapp.com',
    storageBucket: 'card-app-c9c1a.appspot.com',
    measurementId: 'G-YL68RWXG0X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCsFZQAFJbUVffgbRzlhMFZV9lSoLf73WE',
    appId: '1:1025879425987:android:55f7fd592f466cfa3f3376',
    messagingSenderId: '1025879425987',
    projectId: 'card-app-c9c1a',
    storageBucket: 'card-app-c9c1a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCepxbvKT2K_BGwurXSA7vl3mKiVpYTMno',
    appId: '1:1025879425987:ios:6e560f10c96d212c3f3376',
    messagingSenderId: '1025879425987',
    projectId: 'card-app-c9c1a',
    storageBucket: 'card-app-c9c1a.appspot.com',
    iosClientId: '1025879425987-qp9ugsq5fo8h7bg8go03nhbultjrjniv.apps.googleusercontent.com',
    iosBundleId: 'com.example.cardapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCepxbvKT2K_BGwurXSA7vl3mKiVpYTMno',
    appId: '1:1025879425987:ios:6e560f10c96d212c3f3376',
    messagingSenderId: '1025879425987',
    projectId: 'card-app-c9c1a',
    storageBucket: 'card-app-c9c1a.appspot.com',
    iosClientId: '1025879425987-qp9ugsq5fo8h7bg8go03nhbultjrjniv.apps.googleusercontent.com',
    iosBundleId: 'com.example.cardapp',
  );
}
